FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /src
COPY . ./
RUN dotnet tool restore &&\
    dotnet restore && \
    dotnet ef migrations script -i -p Things.Api -o ./migrations.sql

FROM alpine:3.17
WORKDIR /app
RUN rm -rf /var/cache/apk/* && \
    rm -rf /tmp/* && \
    apk update && \
    apk --no-cache add postgresql15-client
COPY ./migrate.sh ./
COPY --from=build /src/migrations.sql .
ENTRYPOINT ["./migrate.sh", "./migrations.sql"]
